apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: veeam2-data-pvc
  namespace: default
  labels:
    app: veeam2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
