apiVersion: v1
kind: Service
metadata:
  name: veeam2-service
  namespace: default
  labels:
    app: veeam2
spec:
  selector:
    app: veeam2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
