apiVersion: v1
kind: Service
metadata:
  name: vmw-ml-analyzer
  namespace: default
spec:
  selector:
    app: vmw-ml-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
